#!/usr/bin/env bash

# Save this file as ~/.config/yadm/bootstrap and make it executable. It will
# execute all executable files (excluding templates and editor backups) in the
# ~/.config/yadm/bootstrap.d directory when run.

set -eu

# Directory to look for bootstrap executables in
BOOTSTRAP_D="${BASH_SOURCE[0]}.d"

if [[ ! -d "$BOOTSTRAP_D" ]]; then
    echo "Error: bootstrap directory '$BOOTSTRAP_D' not found" >&2
    exit 1
fi


bash $BOOTSTRAP_D/package.sh
bash $BOOTSTRAP_D/sudos.sh
bash $BOOTSTRAP_D/editor.sh
bash $BOOTSTRAP_D/settingsync.sh
